<?php

namespace Container0zau4ef;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateReturnOrderHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\ReturnOrder\Application\Command\Create\CreateReturnOrderHandler' shared autowired service.
     *
     * @return \App\ReturnOrder\Application\Command\Create\CreateReturnOrderHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Shared/Application/Command/CommandHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/ReturnOrder/Application/Command/Create/CreateReturnOrderHandler.php';

        return $container->services['App\\ReturnOrder\\Application\\Command\\Create\\CreateReturnOrderHandler'] = new \App\ReturnOrder\Application\Command\Create\CreateReturnOrderHandler(($container->privates['App\\ReturnOrder\\Infrastructure\\Persistence\\Repository\\MongoReturnOrderRepository'] ?? $container->load('getMongoReturnOrderRepositoryService')));
    }
}
