<?php

namespace Container0zau4ef;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarrierReturnCodeStrategyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\ReturnOrder\Domain\Strategy\CarrierReturnCodeStrategy' shared autowired service.
     *
     * @return \App\ReturnOrder\Domain\Strategy\CarrierReturnCodeStrategy
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/ReturnOrder/Domain/Strategy/CarrierReturnCodeStrategy.php';

        return $container->privates['App\\ReturnOrder\\Domain\\Strategy\\CarrierReturnCodeStrategy'] = new \App\ReturnOrder\Domain\Strategy\CarrierReturnCodeStrategy();
    }
}
