<?php

namespace Container0zau4ef;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineMongodb_Odm_DefaultAnnotationMetadataDriverService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'doctrine_mongodb.odm.default_annotation_metadata_driver' shared service.
     *
     * @return \Doctrine\ODM\MongoDB\Mapping\Driver\AnnotationDriver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/Driver/MappingDriver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/Driver/AnnotationDriver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/Driver/AnnotationDriver.php';

        return $container->privates['doctrine_mongodb.odm.default_annotation_metadata_driver'] = new \Doctrine\ODM\MongoDB\Mapping\Driver\AnnotationDriver(($container->privates['annotations.cached_reader'] ?? $container->load('getAnnotations_CachedReaderService')), [0 => (\dirname(__DIR__, 4).'/src/ReturnOrder/Domain')]);
    }
}
