<?php

namespace Container0zau4ef;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFixturesLoaderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Tests\Functional\Contexts\FixturesLoader' shared autowired service.
     *
     * @return \App\Tests\Functional\Contexts\FixturesLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/phpunit/phpunit/src/Framework/Assert.php';
        include_once \dirname(__DIR__, 4).'/vendor/phpunit/phpunit/src/Framework/Reorderable.php';
        include_once \dirname(__DIR__, 4).'/vendor/phpunit/phpunit/src/Framework/SelfDescribing.php';
        include_once \dirname(__DIR__, 4).'/vendor/phpunit/phpunit/src/Framework/Test.php';
        include_once \dirname(__DIR__, 4).'/vendor/phpunit/phpunit/src/Framework/TestCase.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Test/MailerAssertionsTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Test/KernelTestCase.php';
        include_once \dirname(__DIR__, 4).'/tests/Fixtures/FixturesTrait.php';
        include_once \dirname(__DIR__, 4).'/tests/Functional/Contexts/FixturesLoader.php';

        return $container->privates['App\\Tests\\Functional\\Contexts\\FixturesLoader'] = new \App\Tests\Functional\Contexts\FixturesLoader();
    }
}
