<?php

namespace Container0zau4ef;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessengerQueryBusService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Shared\Infrastructure\Bus\Query\MessengerQueryBus' shared autowired service.
     *
     * @return \App\Shared\Infrastructure\Bus\Query\MessengerQueryBus
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Shared/Application/Query/QueryBusInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Shared/Infrastructure/Bus/MessageBusExceptionTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Shared/Infrastructure/Bus/Query/MessengerQueryBus.php';

        return $container->privates['App\\Shared\\Infrastructure\\Bus\\Query\\MessengerQueryBus'] = new \App\Shared\Infrastructure\Bus\Query\MessengerQueryBus(($container->privates['messenger.bus.query'] ?? $container->load('getMessenger_Bus_QueryService')));
    }
}
