<?php

namespace Container0zau4ef;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPickupRequestControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\ReturnOrder\Infrastructure\Http\Controller\PickupRequestController' shared autowired service.
     *
     * @return \App\ReturnOrder\Infrastructure\Http\Controller\PickupRequestController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Shared/Infrastructure/Http/Controller/QueryController.php';
        include_once \dirname(__DIR__, 4).'/src/ReturnOrder/Infrastructure/Http/Controller/PickupRequestController.php';

        return $container->services['App\\ReturnOrder\\Infrastructure\\Http\\Controller\\PickupRequestController'] = new \App\ReturnOrder\Infrastructure\Http\Controller\PickupRequestController(($container->privates['App\\Shared\\Infrastructure\\Bus\\Query\\MessengerQueryBus'] ?? $container->load('getMessengerQueryBusService')), ($container->services['router'] ?? $container->getRouterService()));
    }
}
