<?php

namespace Container0zau4ef;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReturnOrderContextService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Tests\Functional\Contexts\ReturnOrderContext' shared autowired service.
     *
     * @return \App\Tests\Functional\Contexts\ReturnOrderContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/tests/Functional/Contexts/ReturnOrderContext.php';
        include_once \dirname(__DIR__, 4).'/vendor/phpunit/phpunit/src/Framework/Assert.php';
        include_once \dirname(__DIR__, 4).'/vendor/phpunit/phpunit/src/Framework/Reorderable.php';
        include_once \dirname(__DIR__, 4).'/vendor/phpunit/phpunit/src/Framework/SelfDescribing.php';
        include_once \dirname(__DIR__, 4).'/vendor/phpunit/phpunit/src/Framework/Test.php';
        include_once \dirname(__DIR__, 4).'/vendor/phpunit/phpunit/src/Framework/TestCase.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Test/MailerAssertionsTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Test/KernelTestCase.php';
        include_once \dirname(__DIR__, 4).'/tests/Fixtures/FixturesTrait.php';
        include_once \dirname(__DIR__, 4).'/tests/Functional/Contexts/FixturesLoader.php';

        return $container->services['App\\Tests\\Functional\\Contexts\\ReturnOrderContext'] = new \App\Tests\Functional\Contexts\ReturnOrderContext(($container->services['kernel'] ?? $container->get('kernel', 1)), ($container->services['doctrine_mongodb.odm.default_document_manager'] ?? $container->load('getDoctrineMongodb_Odm_DefaultDocumentManagerService')), ($container->privates['App\\Tests\\Functional\\Contexts\\FixturesLoader'] ?? ($container->privates['App\\Tests\\Functional\\Contexts\\FixturesLoader'] = new \App\Tests\Functional\Contexts\FixturesLoader())));
    }
}
