version: '3.7'

services:

    php-fpm:
      build:
        context: .
        dockerfile: ./docker/php-fpm/Dockerfile
      volumes:
        - ./symfony/:/opt/app/
        - "./docker/php-fpm/conf/php-fpm.conf:/etc/php-fpm.conf"
        - "./docker/php-fpm/conf/php.ini:/usr/local/etc/php/conf.d/100-php.ini"

    nginx:
      build: docker/nginx
      volumes:
        - "./docker/nginx/conf/project.conf:/etc/nginx/conf.d/00-project.conf"
      depends_on:
        - php-fpm
      ports:
         - 80:80

    mongodb:
      container_name: mongodb
      image: mongo:latest
      ports:
          - "27017:27017"
