<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7OeBJvF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7OeBJvF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7OeBJvF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7OeBJvF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7OeBJvF\App_KernelDevDebugContainer([
    'container.build_hash' => '7OeBJvF',
    'container.build_id' => 'b1e38541',
    'container.build_time' => 1640332384,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7OeBJvF');
