<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_returnorder_infrastructure_http_createreturnorder__invoke' => [[], ['_controller' => 'App\\ReturnOrder\\Infrastructure\\Http\\Controller\\CreateReturnOrderController'], [], [['text', '/return-order']], [], [], []],
    'app_returnorder_infrastructure_http_pickuprequest__invoke' => [['uuid'], ['_controller' => 'App\\ReturnOrder\\Infrastructure\\Http\\Controller\\PickupRequestController'], [], [['text', '/pickup'], ['variable', '/', '[^/]++', 'uuid', true], ['text', '/return-order']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
