<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Hydrator\HydratorException;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppReturnOrderDomainModelReturnOrderHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate(object $document, array $data, array $hints = array()): array
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoDB\BSON\ObjectId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['customerName']) || (! empty($this->class->fieldMappings['customerName']['nullable']) && array_key_exists('customerName', $data))) {
            $value = $data['customerName'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['customerName']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['customerName']->setValue($document, $return);
            $hydratedData['customerName'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['country']) || (! empty($this->class->fieldMappings['country']['nullable']) && array_key_exists('country', $data))) {
            $value = $data['country'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['country']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['country']->setValue($document, $return);
            $hydratedData['country'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['orderUuid']) || (! empty($this->class->fieldMappings['orderUuid']['nullable']) && array_key_exists('orderUuid', $data))) {
            $value = $data['orderUuid'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['orderUuid']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['orderUuid']->setValue($document, $return);
            $hydratedData['orderUuid'] = $return;
        }
        return $hydratedData;
    }
}