<?php

namespace Container7OeBJvF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_ZBUBs0kService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.ZBUBs0k' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';

        return $container->privates['.messenger.handler_descriptor.ZBUBs0k'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->services['App\\ReturnOrder\\Application\\Query\\PickupRequest\\PickupRequestHandler'] ?? $container->load('getPickupRequestHandlerService')), []);
    }
}
