<?php

namespace Container7OeBJvF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBroadway_ReadModel_RepositoryFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'broadway.read_model.repository_factory' shared service.
     *
     * @return \Broadway\ReadModel\InMemory\InMemoryRepositoryFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/broadway/broadway/src/Broadway/ReadModel/RepositoryFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/broadway/broadway/src/Broadway/ReadModel/InMemory/InMemoryRepositoryFactory.php';

        return $container->services['broadway.read_model.repository_factory'] = new \Broadway\ReadModel\InMemory\InMemoryRepositoryFactory();
    }
}
