<?php

namespace Container7OeBJvF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBroadway_CommandHandling_CommandBusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'broadway.command_handling.command_bus' shared service.
     *
     * @return \Broadway\CommandHandling\SimpleCommandBus
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/broadway/broadway/src/Broadway/CommandHandling/CommandBus.php';
        include_once \dirname(__DIR__, 4).'/vendor/broadway/broadway/src/Broadway/CommandHandling/SimpleCommandBus.php';

        return $container->services['broadway.command_handling.command_bus'] = new \Broadway\CommandHandling\SimpleCommandBus();
    }
}
