<?php

namespace Container7OeBJvF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMongoReturnOrderRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\ReturnOrder\Infrastructure\Persistence\Repository\MongoReturnOrderRepository' shared autowired service.
     *
     * @return \App\ReturnOrder\Infrastructure\Persistence\Repository\MongoReturnOrderRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/ReturnOrder/Domain/Repository/ReturnOrderRepository.php';
        include_once \dirname(__DIR__, 4).'/src/ReturnOrder/Infrastructure/Persistence/Repository/MongoReturnOrderRepository.php';

        return $container->privates['App\\ReturnOrder\\Infrastructure\\Persistence\\Repository\\MongoReturnOrderRepository'] = new \App\ReturnOrder\Infrastructure\Persistence\Repository\MongoReturnOrderRepository(($container->services['doctrine_mongodb.odm.default_document_manager'] ?? $container->load('getDoctrineMongodb_Odm_DefaultDocumentManagerService')));
    }
}
