<?php

namespace Container7OeBJvF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessengerCommandBusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Shared\Infrastructure\Bus\Command\MessengerCommandBus' shared autowired service.
     *
     * @return \App\Shared\Infrastructure\Bus\Command\MessengerCommandBus
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Shared/Application/Command/CommandBusInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Shared/Infrastructure/Bus/MessageBusExceptionTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Shared/Infrastructure/Bus/Command/MessengerCommandBus.php';

        return $container->privates['App\\Shared\\Infrastructure\\Bus\\Command\\MessengerCommandBus'] = new \App\Shared\Infrastructure\Bus\Command\MessengerCommandBus(($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService')));
    }
}
