<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8tYbTRf\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8tYbTRf/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container8tYbTRf.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container8tYbTRf\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container8tYbTRf\App_KernelTestDebugContainer([
    'container.build_hash' => '8tYbTRf',
    'container.build_id' => '87680660',
    'container.build_time' => 1640334766,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8tYbTRf');
